spring.datasource.url=jdbc:postgresql://localhost:5432/immobiliare
spring.datasource.username=postgres
spring.datasource.password=Giulia15
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080
spring.mvc.cors.allowed-origins=http://localhost:4200
upload.dir=uploads
spring.web.resources.static-locations=classpath:/static/,file:uploads/