# Gemini AI
gemini.api.key=AIzaSyAvkNdFvuEf5qNDD4byvUa1V-bd4yNR8As
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent

# Mail
spring.mail.username=TUA_EMAIL@gmail.com
spring.mail.password=TUAAPPPASSWORDSENZASPAZI