# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/immobiliare
spring.datasource.username=postgres
spring.datasource.password=Giulia15
spring.datasource.driver-class-name=org.postgresql.Driver

# Server
server.port=8080

# Upload files
upload.dir=uploads
spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.mvc.static-path-pattern=/**

# Profilo locale
spring.profiles.active=local

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=INSERISCI_EMAIL
spring.mail.password=INSERISCI_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Gemini AI
gemini.api.key=INSERISCI_QUI_LA_CHIAVE
gemini.api.url=INSERISCI_QUI_URL

# App
app.base-url=http://localhost:4200

#Controllo foto
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB

# Sessione ? cookie sicuro e SameSite
server.servlet.session.cookie.same-site=strict
server.servlet.session.cookie.http-only=true
server.servlet.session.timeout=30m

